name: example
description: Gernerate model class from Json files.
version: 0.0.1

environment:
  sdk: ">=3.0.0"

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  json_model:
    path: ../
  json_serializable: ^6.9.4
  
