name: json_model
description: Gernerating Dart model class from Json files with one command.
version: 1.0.0
homepage: https://github.com/flutterchina/json_model
repository: https://github.com/flutterchina/json_model

environment:
  sdk: ">=3.0.0"

dependencies:
  args: ^2.7.0
  build: ^2.4.2
  glob: ^2.1.3
  logging: ^1.3.0
  io: ^1.0.5
  build_runner_core: ^8.0.0
  build_runner: ^2.4.0
  path: ^1.9.1
dev_dependencies:
  test: ^1.5.1
  lint: ^1.0.0
